name: Jersey Data Collection
run-name: ${{ github.actor }} is Collecting data for Jersey 🚀
on:
  schedule:
    - cron: '0,10,20,30,40,50 6-23 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job runs automatically every 15 mins between 6am and 11pm."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::lubridate
            any::tidyr 
            any::stringr
            any::googleCloudStorageR
            any::httr
            any::jsonlite
      - name: Run Script
        run: Rscript -e 'source("google_cloud_build.R")'
      - run: echo "🍏 This job's status is ${{ job.status }}."
